//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _ASP_MVC_Practice.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployee
    {
        public int EmpId { get; set; }
        public string Name { get; set; }
        public int Age { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Position { get; set; }
        public System.DateTime Date_Hired { get; set; }
        public Nullable<System.DateTime> Date_Resigned { get; set; }
        public int PCDetailed { get; set; }
        public bool Status { get; set; }
        public long createDate { get; set; }
        public Nullable<long> modifiedDate { get; set; }
    
        public virtual tblPCDetail tblPCDetail { get; set; }
    }
}
