//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _ASP_MVC_Practice.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPCDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPCDetail()
        {
            this.tblEmployees = new HashSet<tblEmployee>();
        }
    
        public int PCId { get; set; }
        public long ServerIpAddress { get; set; }
        public int ServerPort { get; set; }
        public Nullable<bool> ServerSSL { get; set; }
        public long createDate { get; set; }
        public long modifiedDate { get; set; }
        public string test_Columns { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEmployee> tblEmployees { get; set; }
    }
}
